name: Run application linters and tests.
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: make setup
      - name: Run linters
        run: make lint
      - name: Run tests
        run: make test